### ISSUE TITLE
Watchers are firing

### ISSUE THREAD

**Issue by mastermoo** [pascallaliberte/vue-turbolinks-demo#2]
Hey, @pascallaliberte 

I tried to implement your solution in our Rails app. I was able to get it working more or less.

However, I faced an issue with the watchers that I set. They are firing after I hit the back button. In my case, it does multiple Ajax requests, which is really annoying. Did you face the same problem, or did I miss something? In best case, the data attributes should not trigger a change, when hitting the back button.

Btw, thanks for trying to solve the connection between vue and turbolinks. I think its combination can be very powerful, when it works 😄

**Comment by pascallaliberte** [comment]
Hey @mastermoo, good catch with those watchers firing. Thanks for the kind words too.

I'm thinking I won't be able to fix it centrally, as it is true that restores mutate those properties and watchers get fired.

However, I might be able to do this: expose a property through the mixin called _turbolinksIsDoneRestore set to false until the restore operation is done. You could detect for that property and if available and set to false, in each of your watchers, you could just disable its operation (return the watcher function without doing anything).

How does that sound? Before I try it out, I wanted to get your feedback.

**Comment by mastermoo** [comment]
it sounds really easy on my end! Hopefully not to difficult to implement in your mixin :)

**Comment by pascallaliberte** [comment]
So, I went with an event instead of injecting a local property (makes things cleaner). You can see the details in PR #3 with the updated mixin.

So to implement this in a component:

1. Add your own `_turbolinksDoneRestore` local prop (or name it what you'd like)
2. Add a event listener (using `this.$on`) on `created()`
3. In your watcher, is `_turbolinksDoneRestore` is false, just exit.

```js
  data () {
    return {
      first_name: '',
      last_name: '',
      _turbolinksDoneRestore: false
    }
  },
  created() {
    this.$on('turbolinks:restored', function () {
      this._turbolinksDoneRestore = true
    })
  },
  watch: {
    'first_name': function (newVal, oldVal) {
      if (!this._turbolinksDoneRestore) { return }
      // what's done on change
    }
  }
```

I'm closing this issue. If you see improvements ideas, open a new issue, as usual.

Thanks for pointing this problem out.
